version: '3.1'
services:
  mlflow:
    image: mlflow-server
    container_name: mlflow_server
    build:
      context: ..
      dockerfile:  ./server/Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - <HOST_DIR>:<DOCKER_DIR>
    environment:
      - BACKEND_URI=<BACKEND_URI>
      - ARTIFACT_URI=<DOCKER_DIR>
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <ROOT_PASSWORD>
      MYSQL_DATABASE: <MYSQL_DATABASE>
      MYSQL_USER: <MYSQL_USER>
      MYSQL_PASSWORD: <MYSQL_PASSWORD>
